# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-21 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=200)),
                ('program', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('visit', models.IntegerField(max_length=200)),
                ('month', models.CharField(max_length=200)),
            ],
        ),
    ]
